# Generated by Django 2.0.2 on 2018-03-01 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagedeal',
            name='name',
            field=models.CharField(default='default', max_length=250),
        ),
    ]
