# Generated by Django 2.0.2 on 2018-03-05 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_item_owner'),
        ('ecommerce', '0002_packagedeal_name'),
    ]

    operations = [
    ]
