# Generated by Django 2.0.2 on 2018-03-06 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_auto_20180305_1307'),
        ('ecommerce', '0005_auto_20180306_0836'),
    ]

    operations = [
    ]
