# Generated by Django 2.0.2 on 2018-03-24 09:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0006_merge_20180306_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='sale',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
    ]
