# Generated by Django 2.0.2 on 2018-03-05 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_packagedeal_name'),
        ('ecommerce', '0006_auto_20180305_1255'),
    ]

    operations = [
    ]
