# Generated by Django 2.0.2 on 2018-03-24 20:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0007_auto_20180324_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='package_deal',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(0)]),
        ),
    ]
